DROP TABLE IF EXISTS STUDENTS, FACULTY;

CREATE TABLE STUDENTS
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIO VARCHAR(255),
    AGE INT,
    FACULTY_ID BIGINT
);

CREATE TABLE FACULTY
(
    ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

ALTER TABLE STUDENTS ADD FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(ID);